name: Publish Docs

on:
  workflow_dispatch:

jobs:
  publish-docs:
    runs-on: ["ubuntu-latest"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install pydoc-markdown mkdocs mkdocs-material

      - name: Publish docs
        run: |
          mkdocs gh-deploy